services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    environment:
      - API_KEY=gsk-123123123
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8080:8080"
    networks:
      - app-network
    dns:
      - "8.8.8.8"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge